### ISSUE TITLE
Use cases

### ISSUE THREAD

**Issue by dmalakoudis** [CiudadesAbiertas/vocab-comercio-censo-locales#1]
Hello. I am a collaborator of the professor Andreas Symeonidis. Can you please send me the use cases, because I couldn't find them ?

**Comment by paoespinozarias** [comment]
Hello,
 
You can access to the use cases and user stories in the sidebar of the [wiki](https://github.com/CiudadesAbiertas/vocab-comercio-censo-locales/wiki).

**Comment by dmalakoudis** [comment]
Thank you very much !
